language: python
python:
- '2.7'
- '3.3'
install:
- pip install -r requirements.txt
- pip install pep8
script:
- python tests.py
- pep8 .
deploy:
  provider: heroku
  api_key:
    secure: O7/8FxN1cvfxo/2rtJVsrqZ9VsybpS4x+VuUj5HH2CQyegCcs1dMCOLn3dhAyzCAXyq3rn+Wi8jJuCYNYDYi3Mcl9+mKaA6gkr4Uj9li6IbP1Tu5D8m4ffglZuJnK+pb1TVzPRfhnC4zH95oi95tG0hCyDlxkDMcLY7WzgqIkG9rtcW6UCWkjcSw6paK6Wi/PWsahrUmpgvGt1wnv0kxkFrBqHvuAKuQB+dJ5RlpeZhv1LdGuHo0ErHySOzj54p3ltI4gjZaW4WhRI6yRqQtsK+Fn17BqDS6Xyx9J2uD8HyXd0HJkEHswg/nBtC9GLjGxs3KZxysxnFwckdT98Q2DuYOsyDrkHEzYr/u4ICTiIAU4WFLcqescltui8+RmHk0xzbJFvKzaRbQkhDWvHF3S5ObEa++bJXh0xJd7oFR+m2ypF93LOeoQEMveDi99FjC2ViNwUPf8oYdzgucYeQuYch4XZJEp/0pW0RjInaiU49Pm7hazypAV/Ff4Ar3LXxhXLnTbHwnBf/oS54DSYswGBxwZKawLk8uToIa28ZV1ZedI2SHSa1BQrksgHTGAG8hL7cZIKSgjaWqhAy6CVHPoYljR48IghubxX3dfuiMa9IluWs0UCoAdYyaKqqGxSKE3ElGNhT9oRs0ZRRqA3sWWzU/ZzYEvNShLdjVmgg7lUc=
  app: myles-api
  on:
    repo: myles/me-api
