language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install pep8
- pip install demjson
script:
- python tests.py
- pep8 .
- jsonlint -s data/*.json
deploy:
  provider: heroku
  api_key:
    secure: KlF7NK3lH9js+v7qhHtvLpg5Gb+XpJOlWz3AJaNfxalBUdMvaxjeWgbI3tk8aNgf1sw4HVJU1rhPp/U3724GHhyv8qCm40WXaiDWZ/pm/kY47h9PWdFTM83P82H6MtU1PdTgEK0T7lKiATMqjaBHS7X+u2uI9CCtrqDFilVmu3mb0oE7gne/QguKw8uXJVokXvV8XRDkPkNbyabpcg5fl+s0ffepsmFe81EQZn97OIk3uvfDIFKk8LKtP02Zsjihzg0zDxVA0Q4byPtUhccXtfmCjNdPRagLohiTTPACa9cQPx1hVrHaWNE4bqOkz8l2FamWrgsQeGvKz4wV/b4CljbN6UNWMzMslYxxQqp8YnpIstv0mqXBoUI80vFxd3fy+WTWOPkYV0zRgj6KzY8UqhB+hqBL9bvDnyTAyX8/SuctYbmsIvtYHe0wo9Z7foToP5qneSQYyd+yJQwgUK6+oYqMM/UGlWackFkLl5V8xmVaaC82SuP39QDfQg6vh9agFhtWkbh5beId5quIscAdUq7Td8Z83nm5G44NNzL/fLPzXfFOKTPPMPyW8GBFheTDSbGlzgqR2ujIxB1egi7/0xUWHREtAHy+mqtkLo5cJfpXGC+hMYwORjxUxgsQGd0vUCwGVe6s0vGMZRtYmhdWtM+LIlA4rBgtKAaz+bsKqoI=
  app:
    master: myles-api
    develop: staging-myles-api
  on:
    repo: myles/me-api
